# config.py
RESIZE_WIDTH = 320
FPS_ASSUMED = 30
BUFFER_SECONDS = 3.0
BUFFER_SIZE = int(FPS_ASSUMED * BUFFER_SECONDS)

MOTION_EMA_ALPHA = 0.2
VELOCITY_SMOOTH_FRAMES = 5
BASELINE_CALIBRATION_SECONDS = 0

MOTION_NOISE_FLOOR = 0.32
ENERGY_NOISE_FLOOR = 7.71

FALL_VELOCITY_THRESHOLD = 0.06
FALL_CONFIRMATION_FRAMES = 4

FREQ_NORMAL_LOW = 0.1
FREQ_NORMAL_HIGH = 2.0
FREQ_SEIZURE_LOW = 2.0
FREQ_SEIZURE_HIGH = 7.0

MOTION_THRESHOLD = 0.7
FALL_TRIGGER_SENSITIVITY = 0.5
DURATION_THRESHOLD = 15
COOLDOWN_FRAMES = 90

HEAD_SHAKE_THRESHOLD = 0.9
FACIAL_DISTORTION_THRESHOLD = 0.6
MOUTH_OPEN_THRESHOLD = 0.18
TREMOR_THRESHOLD = 0.39

FG_HISTORY = 300
FG_VAR_THRESHOLD = 20
FG_MIN_AREA_RATIO = 0.005
FG_STABILITY_THRESHOLD = 0.2
FG_LOST_FRAMES_MAX = 15

MIN_ROI_RATIO = 0.05

ALERT_COOLDOWN_SECONDS = 40
ALERT_SOUND_DURATION = 30
ALERT_CONFIG_FILE = "data/alert_config.json"
