# config.py
"""Seizure Detection System Configuration"""

# Camera & Processing
RESIZE_WIDTH = 320
FPS_ASSUMED = 30
BUFFER_SECONDS = 3.0
BUFFER_SIZE = int(FPS_ASSUMED * BUFFER_SECONDS)

# Signal Processing
MOTION_EMA_ALPHA = 0.2
VELOCITY_SMOOTH_FRAMES = 5
BASELINE_CALIBRATION_SECONDS = 0

# Noise Gate
MOTION_NOISE_FLOOR = 0.37
ENERGY_NOISE_FLOOR = 11.8

# Fall Detection
FALL_VELOCITY_THRESHOLD = 0.06
FALL_CONFIRMATION_FRAMES = 4

# Spectral Analysis
FREQ_NORMAL_LOW = 0.1       
FREQ_NORMAL_HIGH = 2.0
FREQ_SEIZURE_LOW = 2.0
FREQ_SEIZURE_HIGH = 6.5     

# Decision Logic
MOTION_THRESHOLD = 0.70
FALL_TRIGGER_SENSITIVITY = 0.7 
DURATION_THRESHOLD = 20
COOLDOWN_FRAMES = 120

# Foreground Isolation
FG_HISTORY = 300              
FG_VAR_THRESHOLD = 20         
FG_MIN_AREA_RATIO = 0.005     
FG_STABILITY_THRESHOLD = 0.2  
FG_LOST_FRAMES_MAX = 15       

# ROI Validation
MIN_ROI_RATIO = 0.05

# Alert System
ALERT_COOLDOWN_SECONDS = 30
ALERT_SOUND_DURATION = 5
ALERT_CONFIG_FILE = "data/alert_config.json"
